#!/bin/bash

HOW_MANY_WINDOW=$(sudo tmux list-windows | grep "panes" | head -n 1 | cut -f1 -d")" | awk -F'(' '{print $2}' | sed 's/[^.0-9]*//g')

if [ "$HOW_MANY_WINDOW" -gt "2" ]; then
  ps aux | grep "wrapper" | grep "minerstat" | awk '{print $2}' | sudo xargs kill -9
  sudo tmux split-window 'sudo /home/minerstat/minerstat-os/core/wrapper' \;
  sudo tmux swap-pane -s 1 -t 0 \;
fi
